name: Compress Images to AVIF

on: [push]

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Squoosh CLI
      run: npm install @squoosh/cli -g

    - name: Compress Images to AVIF and Log Size
      run: |
        mkdir -p after
        for file in $(find . -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \)); do
          originalSize=$(du -m "$file" | cut -f1)
          squoosh-cli --avif '{"cqLevel":33}' "$file"
        done
        for compressedFile in $(find . -type f -iname \*.avif); do
          if [ -f "$compressedFile" ]; then
            mv "$compressedFile" "after/"
            compressedSize=$(du -m "after/$(basename "$compressedFile")" | cut -f1)
            echo "Compressed size: ${compressedSize}MB"
          else
            echo "Error: Compressed file not found - $compressedFile"
          fi
        done

    - name: Deploy Compressed Images to 'after' Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: after  # 目标分支
        folder: after  # 需要部署的文件夹
        commit-message: "Deploy compressed images"
        clean: true
        single-commit: true
        force: true
        ssh-key: ${{ secrets.MY_SSH_PRIVATE_KEY }}  # Use the new token







