name: Compress Images to AVIF

on: [push]

jobs:
  optimize-images:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Squoosh CLI
      run: npm install @squoosh/cli -g

    - name: Compress Images to AVIF and Log Size
      run: |
        $files = Get-ChildItem -Path . -Recurse -Include *.jpg, *.jpeg, *.png
        foreach ($file in $files) {
          $originalSize = (Get-Item $file).length / 1MB
          squoosh-cli --avif '{"cqLevel":33}' --output-dir $(Split-Path $file) --output-format avif $file
          $compressedFile = (Join-Path $(Split-Path $file) ($file.BaseName + '.avif'))
          $compressedSize = (Get-Item $compressedFile).length / 1MB
          Write-Output "Original size of $($file.Name): $originalSize MB, Compressed size: $compressedSize MB"
        }
