name: sync


on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: "s110b/qq"
          branch: gh-pages
          folder: ./
          clean: true
          single-commit: true
          force: true
          ssh-key: ${{ secrets.MY_SSH_PRIVATE_KEY }}  # Use the new token
