name: sync


on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: app
      - name: Install tree and Print Directory Structure After Checkout
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: "s110b/qq"
          branch: qq
          folder: ./app
          clean: true
          single-commit: true
          force: true
          ssh-key: ${{ secrets.MY_SSH_PRIVATE_KEY }}  # Use the new token
      - name: Print Directory Structure After Deploy
        run: tree app
