name: sync


on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  notion2markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    name: Convert Notion to Markdown
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
	with:
          ref: gh-pages

	  

