name: sync


on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  notion2markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
	with:
          ref: 'gh-pages'

